### ISSUE TITLE
.NET 4.x Api Compatibility

### ISSUE THREAD

**Issue by sasa42** [keijiro/jp.keijiro.apriltag#1]
Is it possible to implement .NET 4.x Api Compatibility.

Only .Net Standard 2.0 is working for now in unity 20202.2f1.

**Comment by keijiro** [comment]
It's technically possible to add .NET 4.x support, but I strongly recommend migrating to .NET Standard.

Out of curiosity, why do you still use .NET 4.x?

**Comment by keijiro** [comment]
I'm closing this issue as I can't find any strong motive to solve it at the moment. Please feel free to reopen it for further discussion.
