### ISSUE TITLE
Help wanted for AR Foundation integration

### ISSUE THREAD

**Issue by elvis75k** [keijiro/jp.keijiro.apriltag#10]
I would like a to integrate this amazing tool into AR Foundation.
How can I use the AR camera stream to track the tags; being able to trace images in a unity scene instead of a webcam would probably also be a useful advance/hint,

thank you.

**Comment by keijiro** [comment]
The tag detector processes an image, not a webcam. The webcam support is implemented in the sample program.

So, I think you can do it in the current implementation.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by elvis75k** [comment]
I'm not so smart yet and i have not found any solution to modify and take advantage of the webcam sample to work with an image or a render texture instead. I tried to set up Render Texture or a Texture2D instead of the WebCamTexture but this doesn't make sense. Could you help me to implement this?

thank you.

**Comment by elvis75k** [comment]
I have managed to crash unity instantly with this :) [PictureTest.cs](https://gist.github.com/elvis75k/329b35089361ac5739f7ae746d6deb4e)

**Comment by keijiro** [comment]
Is the dimensions of `sourceImage` correct? My wild guess is that the texture importer changed the dimensions to a power-of-two square.

**Comment by elvis75k** [comment]
After changing the read/write parameter = true and set the Non-Power of 2 to none in the sourceImage importer it just works!

Thank you.

![Screenshot 2021-11-06 at 11 22 22](https://user-images.githubusercontent.com/49713529/140606296-d0995fae-b370-43f8-8809-91bf425923a0.png)

**Comment by elvis75k** [comment]
Thanks Keijiro for pointing me in the right direction, i have learned a lot...

https://user-images.githubusercontent.com/49713529/140614561-d452d7f0-9f22-4e0e-ae2d-acc2d763ec8a.mov
