### ISSUE TITLE
Errors building IOS binaries

### ISSUE THREAD

**Issue by starlprd** [keijiro/jp.keijiro.apriltag#11]
<img width="1440" alt="Screenshot 2022-11-01 at 6 54 48 PM" src="https://user-images.githubusercontent.com/46620033/199917417-555a27bb-13e6-4f55-a060-f669fb410b78.png">
<img width="1440" alt="Screenshot 2022-11-01 at 6 54 55 PM" src="https://user-images.githubusercontent.com/46620033/199917427-1cdc965d-724e-44c2-8102-90dfb20a5930.png">
i couldn't raise a issue on the main repo so posting it here. I have made binaries for other platforms and those are working with unity but facing this problem while making for IOS, could you please help me with this or show some directions how i can solve that.
Thank you in advance.

**Comment by keijiro** [comment]
Are you using Intel MacBook?

**Comment by starlprd** [comment]
> Are you using Intel MacBook?
yes I am using intel MacBook

**Comment by starlprd** [comment]
> Are you using Intel MacBook?

yes I am using intel MacBook

**Comment by keijiro** [comment]
I'm using M1 (arm64) Mac, so I didn't have to change the architecture to build the plugin. You need to add an arch option to the Makefile. I don't know which one is needed, though.

**Comment by starlprd** [comment]
that could explain the IOS build but I did complete macOS plugin without errors. I have to check if I could make it with M1(arm64).Even I don't know about any arch options. If you could make the plugin for 36h11 for me it would be helpful. Also did you install xcode or it was done without it by just using command line tools?
Thank you for response.

**Comment by keijiro** [comment]
>  If you could make the plugin for 36h11 for me it would be helpful.

I don't know about any arch options either.

**Comment by starlprd** [comment]
I have built the binaries on m2 and it worked without any errors. Thanks for that piece of advice.
