### ISSUE TITLE
Help Wanted to add camera calibrated values

### ISSUE THREAD

**Issue by sanarco1** [keijiro/jp.keijiro.apriltag#7]
Hello keijiro, 

Your work is amazing and helped a lot. Although, I need a small help. Is it possible to add the calibration values in the project (or to the camera frame)? 
I am getting my camera's calibration values from this link: http://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration

Thanks in advance.

**Comment by keijiro** [comment]
Is this actually relevant to Apriltag? As far as I know, Apriltag doesn't provide any camera calibration functionality.

**Comment by sanarco1** [comment]
Actually I want the world coordinates of the detected Apriltags, If the rgb camera is calibrated, it would give accurate TagPose. In the repo you have mentioned to provide rbg camera's FoV  to  Unity's camera FoV for better estimation of position. In the same way if we provide the calibration matrix in the code we can get better pose estimation.

**Comment by keijiro** [comment]
> In the repo you have mentioned to provide rbg camera's FoV to Unity's camera FoV for better estimation of position. 

I provide camera's FoV because Apriltag uses FoV to estimate tag poses.

> In the same way if we provide the calibration matrix in the code we can get better pose estimation.

Apriltag doesn't accept a calibration matrix.

Or, do you have any idea about how to use a calibration matrix with Apriltag?

**Comment by sanarco1** [comment]
> I provide camera's FoV because Apriltag uses FoV to estimate tag poses.

Yes, and it works as expected.

> Apriltag doesn't accept a calibration matrix.

Yes, Apritag will not accept calibration matrix but we have to provide the calibration matrix to the camera frames.

> Or, do you have any idea about how to use a calibration matrix with Apriltag?

That would be my primary question.

Imagine if we try to measure the distance (Vector3.Distance()) from camera origin to the detected tag OR distance between two detected tags and compare it with by using a real measurement scale (measurement tape or a ruler). That distance should closely match with the real distance. This is what I am trying to match.

**Comment by keijiro** [comment]
Please understand that the main aim of this project is just providing a thin wrapper of the Apriltag library. Adding an extra functionality is out of its scope.

The simple answer to your question is, no, I have no firm idea about it. I have never done research on this field.

It sounds interesting, but unfortunately, I don't have enough time for it.

**Comment by sanarco1** [comment]
Ok, got it. Thanks a lot for the update.
