### ISSUE TITLE
How I transfer the tag position to world coordinate?

### ISSUE THREAD

**Issue by robert0126** [keijiro/jp.keijiro.apriltag#8]
Hi, I have a few questions about the tag position?
Why is the value of tag position always between 0 to 1, and how can I transfer the value to the unity world coordinate?
I have already tried the ViewportToWorldPoint script method, but the result was so weird.

**Comment by keijiro** [comment]
There is no information to bind the camera coordinates to the world coordinates -- It doesn't know where the world origin (0, 0, 0) is nor which direction is "forward". You have to define it that is optimal for your application. For example, define "Origin" tag and keep it in the camera view, or use the first-found tag as an origin.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by robert0126** [comment]
OK. And why the values are all limited in 0 to 1, are they limited in which scripts?

**Comment by keijiro** [comment]
They're not limited but by-design behavior of the apriltag pose estimator.
